# https://fabricmc.net/develop/

[versions]
# Fabric versions
fabricMinecraft = "1.21.11"
fabricLoader = "0.18.4"
fabricApi = "0.141.1+1.21.11"

# NeoForge version
neoforge = "21.11.25-beta"

# Quilt versions
quiltLoader = "0.30.0-beta.0"

# Video versions
newpipeExtractor = "v0.24.8"
gst1 = "1.4.0"
javacpp = "1.5.12"
ffmpeg = "7.1.1-1.5.12"
javacv = "1.5.12"

# Utils and other versions
utils = "1.4.10"
jspecify = "1.0.0"
adventure = "4.26.1"
adventurePlatform = "4.4.1"

# Build tool versions
loom = "1.15.0-alpha.25"
moddev = "2.0.137"
shadow = "9.3.0"

[libraries]
# Fabric dependencies
fabricMinecraft = { module = "com.mojang:minecraft", version.ref = "fabricMinecraft" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }

# Quilt dependencies
quiltLoader = { module = "org.quiltmc:quilt-loader", version.ref = "quiltLoader" }

# Video dependencies
newpipeExtractor = { module = "com.github.TeamNewPipe:NewPipeExtractor", version.ref = "newpipeExtractor" }
gst1 = { module = "org.freedesktop.gstreamer:gst1-java-core", version.ref = "gst1" }
javacpp = { module = "org.bytedeco:javacpp", version.ref = "javacpp" }
ffmpeg = { module = "org.bytedeco:ffmpeg", version.ref = "ffmpeg" }
javacv = { module = "org.bytedeco:javacv", version.ref = "javacv" }

# Utils and other dependencies
utils = { module = "me.inotsleep:utils", version.ref = "utils" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventurePlatform = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventurePlatform" }
